services:
  consul:
    image: consul:1.15.4
    ports:
      - "8500:8500"
      - "8600:8600"
    networks:
      - soa-network
    command: agent -server -ui -node=consul-server -bootstrap-expect=1 -client=0.0.0.0


  haproxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "8404:8404"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./haproxy-ssl.pem:/usr/local/etc/haproxy/haproxy-ssl.pem:ro
      - ./errors/429.http:/usr/local/etc/haproxy/429.http:ro
      - ./errors/503.http:/usr/local/etc/haproxy/503.http:ro
    environment:
      - SLEEP_TIME=100
      - SERVICES=ticketService
      - CONFIG_PATH=/usr/local/etc/haproxy/haproxy.cfg
      - CONSUL_ADDR=consul:8500
    networks:
      - soa-network

networks:
  soa-network:
    driver: bridge

